// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Tags        []string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
