// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"
)

type Querier interface {
	CountItems(ctx context.Context, arg CountItemsParams) (int64, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	GetItemByID(ctx context.Context, id int64) (Item, error)
	GetItemByIDForUpdate(ctx context.Context, id int64) (Item, error)
	PatchItemOptimistic(ctx context.Context, arg PatchItemOptimisticParams) (Item, error)
	SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error)
	SearchItemsKeysetNext(ctx context.Context, arg SearchItemsKeysetNextParams) ([]Item, error)
	SearchItemsKeysetPrev(ctx context.Context, arg SearchItemsKeysetPrevParams) ([]Item, error)
	UpsertItemBySlug(ctx context.Context, arg UpsertItemBySlugParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
